- name: Add APT key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
    tags: installmongo

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    tags: installmongo

- name: Install mongodb package
  apt:
    name: mongodb-org
    allow_unauthenticated: yes
    state: present
    tags: installmongo

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
  tags: installmongo
